@echo off

:: %License%

SetLocal DisableDelayedExpansion

set Result=1

set TextFileExtensions=( ^
.             ^
accessor      ^
acs           ^
ada           ^
adb           ^
addin         ^
ads           ^
ahk           ^
am            ^
ammo          ^
arena         ^
as            ^
asa           ^
asc           ^
asm           ^
asp           ^
atr           ^
au3           ^
aut           ^
aux           ^
awk           ^
axl           ^
bas           ^
bash_history  ^
bat           ^
bhc           ^
bcf           ^
body          ^
bot           ^
bsh           ^
c             ^
camera        ^
cat           ^
cbd           ^
cbl           ^
cc            ^
cd            ^
cdb           ^
cdc           ^
cdf           ^
cfg           ^
cfm           ^
cgi           ^
cls           ^
clw           ^
cmake         ^
cmd           ^
cnf           ^
cnt           ^
cob           ^
conf          ^
config        ^
cpp           ^
cs            ^
csdl          ^
csproj        ^
css           ^
csv           ^
ctl           ^
cue           ^
cxx           ^
d             ^
datasource    ^
def           ^
defs          ^
dfm           ^
diff          ^
diz           ^
dob           ^
docbook       ^
dotsettings   ^
djs           ^
dox           ^
dpk           ^
dpr           ^
dsm           ^
dsp           ^
dsr           ^
dsw           ^
dtd           ^
dtl           ^
dxf           ^
ebs           ^
eco           ^
edg           ^
edmx          ^
efx           ^
ent           ^
err           ^
f             ^
f2k           ^
f90           ^
f95           ^
fd            ^
fdf           ^
filters       ^
fgl           ^
fif           ^
for           ^
frames        ^
frm           ^
g2skin        ^
gametype      ^
generate      ^
git           ^
gitattributes ^
gitconfig     ^
gitignore     ^
gitmodules    ^
gore          ^
gradle        ^
gsc           ^
h             ^
hh            ^
hhc           ^
hhk           ^
hhp           ^
hm            ^
hpj           ^
hpp           ^
hs            ^
hta           ^
htaccess      ^
htd           ^
htm           ^
html          ^
htpasswd      ^
htt           ^
hud           ^
hxa           ^
hxc           ^
hxk           ^
hxt           ^
hxx           ^
idl           ^
idx           ^
il            ^
iml           ^
impacts       ^
inc           ^
inf           ^
ini           ^
inl           ^
instance      ^
inview        ^
ipr           ^
isl           ^
iss           ^
itcl          ^
item          ^
iws           ^
java          ^
jmconfig      ^
jnl           ^
jpo           ^
js            ^
json          ^
jsfl          ^
jsp           ^
kix           ^
kml           ^
las           ^
lhs           ^
lic           ^
linq          ^
lisp          ^
list          ^
litcoffee     ^
log           ^
lref          ^
lsp           ^
lst           ^
lua           ^
m             ^
m4            ^
mak           ^
manifest      ^
map           ^
mapcycle      ^
master        ^
material      ^
mc            ^
md            ^
mdl           ^
menu          ^
met           ^
metagen       ^
miscents      ^
mission       ^
mk            ^
mke           ^
ml            ^
mli           ^
mnu           ^
mpt           ^
ms            ^
msgsrc        ^
msha          ^
msl           ^
mst           ^
mx            ^
name          ^
natvis        ^
nav           ^
nfo           ^
npc           ^
nsh           ^
nsi           ^
nt            ^
objectives    ^
odl           ^
ora           ^
orderedtest   ^
outfitting    ^
pag           ^
pas           ^
patch         ^
pcf           ^
php           ^
php3          ^
php4          ^
phtml         ^
per           ^
pl            ^
player        ^
pln           ^
plx           ^
pm            ^
po            ^
pod           ^
portable      ^
pot           ^
poses         ^
pp            ^
ppk           ^
prj           ^
pro           ^
proj          ^
properties    ^
props         ^
prp           ^
ps            ^
ps1           ^
ps1xml        ^
psc1          ^
psm1          ^
ptl           ^
pub           ^
py            ^
pyproj        ^
pyw           ^
q3asm         ^
qe4           ^
r             ^
rb            ^
rbw           ^
rc            ^
rc2           ^
rdf           ^
rdp           ^
recent        ^
reg           ^
rej           ^
rep           ^
resx          ^
rge           ^
rgs           ^
rgt           ^
rmd           ^
rqe           ^
rqp           ^
rul           ^
ruleset       ^
sam           ^
sample        ^
scm           ^
script        ^
ses           ^
settings      ^
sf            ^
sh            ^
shl           ^
shader        ^
shfbproj      ^
shock         ^
shtm          ^
shtml         ^
sif           ^
skl           ^
sln           ^
sma           ^
smd           ^
sml           ^
snippet       ^
sp            ^
spb           ^
spec          ^
sps           ^
sql           ^
ss            ^
ssdl          ^
st            ^
str           ^
sty           ^
stype         ^
sub           ^
suit          ^
sun           ^
sv            ^
svg           ^
svh           ^
sxl           ^
t             ^
targets       ^
tcl           ^
teams         ^
terrain       ^
testrunconfig ^
testsettings  ^
tex           ^
theme         ^
thy           ^
tlh           ^
tli           ^
tmplt         ^
toc           ^
tpl           ^
trx           ^
tsb           ^
tt            ^
ttinclude     ^
tui           ^
tuo           ^
txt           ^
ui            ^
url           ^
user          ^
v             ^
vb            ^
vbg           ^
vbp           ^
vbproj        ^
vbr           ^
vbs           ^
vbw           ^
vcproj        ^
vcs           ^
vcxproj       ^
vdproj        ^
vh            ^
vhd           ^
vhdl          ^
voice         ^
vscontent     ^
vsdir         ^
vsmdi         ^
vsprops       ^
vspscc        ^
vssettings    ^
vssscc        ^
vstdir        ^
vstheme       ^
vsz           ^
vts           ^
vxml          ^
vws           ^
wixlib        ^
wixobj        ^
wixproj       ^
wml           ^
wnt           ^
wpn           ^
wri           ^
wsdl          ^
wsf           ^
wxl           ^
wxs           ^
xaml          ^
xdc           ^
xhtml         ^
xlf           ^
xliff         ^
xml           ^
xmt           ^
xrc           ^
xsd           ^
xsl           ^
xslt          ^
xsml          ^
xul           ^
yml           ^
)

set Arg1=%1
SetLocal EnableDelayedExpansion
if not .!Arg1! == . EndLocal & call :Usage & goto Exit
EndLocal


:DoWork
set Result=0
echo Adding a plain text persistent handler for the following extensions:
echo.
for %%a in %TextFileExtensions% do (
    echo | set /p= %%a 
    call "%~dp0AddTextFileExtension.bat" "%%a" >nul
    if %ErrorLevel% neq 0 set Result=1
)

goto Exit


:Usage
SetLocal EnableDelayedExpansion
echo.
echo Adds a plain text handler for the following file extensions, allowing files with the extension to be indexed, searched, and easily opened in any text editor:
echo. 
for %%a in %TextFileExtensions% do (
    set AllExts=!AllExts!%%a 
)
echo !AllExts!
echo.
echo.%~n0 ^<No Parameters^>
exit /b


:Exit
call "%~dp0PauseGui.bat" "%~f0"
@%ComSpec% /c exit %Result% >nul
